- hosts: localhost
  gather_facts: false

  tasks:

    - name: Spin up Windows 2019 base t2.micro instance(s) in us-east-1
      ec2:
        key_name: '{{ key }}'
        group: '{{ group }}' #add security group(s)
        instance_type: t2.micro
        image: ami-032c2c4b952586f02 #specific to region
        count: '{{ count }}' #how many instances to initiate
        region: us-east-1 
        wait: true
